import React, {Component, useLayoutEffect} from 'react';
import './Game.css';

export class Game extends Component {
    constructor(props) {
        super(props);
        let time = 500;
        if(this.props.difficulty){
            time = 200;
        }
        this.state = {
            squares: Array(4).fill(0),
            time: time,
            moves : 0,
            score: 0,
            headerState : 0,
            pattern : [0, 1, 2, 3],
            showColor : "",
            colors: ["red", "blue", "yellow", "green"],
            inGame: false,
            name: "Stranger",
        }

    }

    /**
     * Generates a new round by creating a new pattern and then displaying it.
     */
    handleRound() {
        let pattern = []
        for (let i = 0; i < 5; i++){
            pattern.push(Math.floor(Math.random() * 4))
        }
        this.setState({pattern: pattern, headerState : 1, inGame: false})
        this.showColors(pattern).then()
    }

    /**
     * Displays the colors generated by handleRound()
     * @param pattern color to display
     * @returns {Promise<void>} nothing
     */
    async showColors(pattern){
        for (let index of pattern) {
            this.setState({showColor: index});
            await new Promise(r => setTimeout(r, this.state.time));
            this.setState({showColor: -1});
            await new Promise(r => setTimeout(r, this.state.time/2));
        }
        this.setState({headerState: 0, inGame: true})
    }

    handleHeaderState(){
        const level = this.state.level;
        const name = this.state.name;
        if(this.state.score === -1 ){
            return(
                <div id="colorHeader">
                    <p id="gameOver"> {name} LOST :( </p>
                </div>
            )
        }
        if(this.state.headerState === 0){
            return(
                <div id="colorHeader">
                    <button id="newRoundButton" onClick={() => this.handleRound(level)}> Start Round</button>
                </div>
            )
        }
        else if(this.state.headerState === 1){

            return(
                <div id="colorHeader">
                    <Color showColor={this.state.showColor} colors={this.state.colors}/>
                </div>
            );
        }
    }

    /**
     * Handles what happens when user clicks on one of the four squares.
     * @param i index of square clicked
     */
    handleClick(i) {
        const pattern = this.state.pattern;
        let inGame = this.state.inGame;
        let moves = this.state.moves;
        let score = this.state.score;
        if(inGame) {
            let all = makeMove(moves, score, i, pattern, inGame);
            moves = all[0];
            score = all[1];
            inGame = all[2];
            this.setState({
                    moves: moves,
                    score: score,
                    inGame: inGame,
                }
            )
        }
    }

    handleChange(){
        this.setState({
            name: document.getElementById('fname').value
        })
    }

    render(){
        const squares = this.state.squares;
        const score = this.state.score;
        return(
            <div className="container">
                <p>Your name:<br></br>
                    <input onChange={() => this.handleChange()} type="text" id="fname" name="fname"/>
                </p>
                {this.handleHeaderState()}
                <Board squares={squares} onClick={i => this.handleClick(i)} colors={this.state.colors}/>
                <Score score={score}/>
            </div>
        );
    }
}

/**
 * Constructs the board of Simon Says which consists of 2x2 squares.
 */
class Board extends Component {
    renderSquare(i) {
        return (
            <button className="square" id={this.props.colors[i]}
                    value={this.props.squares[i]}
                    onClick={() => this.props.onClick(i)}
                    key={this.props.colors[i]}
            />
        )
    }
    render() {
        return(
            <div id="board">
                {this.renderSquare(0)}
                {this.renderSquare(1)}
                {this.renderSquare(2)}
                {this.renderSquare(3)}
            </div>
        )
    }
}

/**
 * Score component on the bottom of the screen.
 */
class Score extends Component {

    render() {
        const score = this.props.score
        return (
            <div id="scoring">
                <p align="right">
                    Score: {score}
                </p>
            </div>

        )

    }
}

/**
 * This is the section that renders the colors that the users are shown in the beginning.
 */
class Color extends Component {
    render() {
        const color = this.props.showColor;
        const colors = this.props.colors;
        return (
            <p id={colors[color]}></p>
        )
    }
}

/**
 * Triggered when a move is made by the player in game.
 * @param moves step of movement by player
 * @param score total score
 * @param i index/color chosen by player
 * @param pattern pattern to match
 * @param inGame player in game?
 * @returns {(number|boolean)[]} output of states
 */
export function makeMove(moves, score, i, pattern, inGame){
    if (pattern[moves] === i) {
        moves += 1;
    } else {
        moves = 0;
        score = -1;
    }
    if (moves >= pattern.length){
        score += 1;
        moves = 0;
        inGame = false;
    }
    return [moves, score, inGame];
}
